<?php
namespace Ass\Mapping;
use Attribute as Attribute;
#[Attribute(Attribute::TARGET_PROPERTY)]
final class Column{
    public function __construct(
        public ?string $name = null,     /** name that maps to attribute name in db */
        public ?string $type = null,    /** Type that maps to vendor-specific db types */
        public ?int $length = null,     /** length in case of string(varchar, text) or binary objects */
        public ?int $precision = null,  /** precision in case of decimals */
        public bool $unique = false,    /** equivalent to UNIQUE constraint */
        public bool $nullable = false, /** equivalent to opposite of NOT NULL */
        public bool $insertable = true, /** is it automatically generated by db or inserted by Entity (for eg; id) */
        public bool $updatable = true, /** in my case, if medicine name is once inserted, I need to remove the instance (row) and re-insert the row with new name which makes this attribute immutable */
        public bool $auto = false /** equivalent to auto_increment */
    ){}
}
